on: push
name: SamKirkland/web-deploy
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.FTP_SERVER }}
        remote-user: ${{ secrets.FTP_USERNAME }}
        private-ssh-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        destination-path: /var/www/stage.hellomed.com/wp-content/
